unit udmLDJam52_Icones_AS303523361;
{
  Unit generated by folder2FMXImageList the 08/01/2023 18:52:17

  Don't change it if you want to refresh the images by the program :
  it will erase all your changes !

  ******************************************************************************
  * Folder2FMXImageList
  ******************************************************************************
  (c) Patrick Prémartin - Olf Software

  Source : https://github.com/DeveloppeurPascal/Folder2FMXImageList
  Issue : https://github.com/DeveloppeurPascal/Folder2FMXImageList/issues
  New features : https://github.com/DeveloppeurPascal/Folder2FMXImageList/discussions
  Download : https://folder2fmximagelist.olfsoftware.fr/
}
interface

uses
  System.SysUtils, System.Classes, System.ImageList, FMX.ImgList;

type
  TdmLDJam52_Icones_AS303523361 = class(TDataModule)
    ImageList: TImageList;
  private
    { Déclarations privées }
  public
    { Déclarations publiques }
  end;

var
  dmLDJam52_Icones_AS303523361: TdmLDJam52_Icones_AS303523361;

implementation

{%CLASSGROUP 'FMX.Controls.TControl'}

{$R *.dfm}

end.
